version: '3.8'

services:
  app:
    build: .
    container_name: interview-scheduler-api
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/interview_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq

  db:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: interview_db
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6380:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-queue
    ports:
      - "5673:5672"
      - "15673:15672"

volumes:
  mysql-data:

